# Generated by Django 4.2.6 on 2023-11-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctionHouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="image",
            field=models.ImageField(null=True, upload_to="auction_images"),
        ),
        migrations.DeleteModel(
            name="AuctionImage",
        ),
    ]
