# Generated by Django 4.2.6 on 2023-11-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "auctionHouse",
            "0003_alter_auction_highest_bid_alter_auction_winner_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Pending", "Pending"),
                ],
                max_length=30,
            ),
        ),
    ]
