# Generated by Django 4.2.6 on 2023-11-28 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auctionHouse", "0005_alter_auction_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="highest_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="auction",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_auction",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
