# Generated by Django 4.2.6 on 2023-11-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctionHouse", "0007_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Pending", "Pending"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=30,
            ),
        ),
    ]
