# Generated by Django 4.2.6 on 2023-11-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionHouse', '0012_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='ups_tracking_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
