# Generated by Django 4.2.6 on 2023-12-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctionHouse', '0013_shipping_ups_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
